parserOptions:
    ecmaVersion: 6
    sourceType: module

extends: "eslint:recommended"

env:  {
    browser: true,
    node: true
}

globals: {
    APP_NAME
}

rules:
    no-console:
    - warn
    quotes:
    - error
    - single
    - {
        avoidEscape: true
    }
    prefer-const:
    - warn
    no-var:
    - error
    func-call-spacing:
    - error
    - never
    space-before-function-paren:
    - error
    - {
        anonymous: always,
        named: never,
        asyncArrow: always
    }
    arrow-spacing:
    - error
    - {
        before: true,
        after: true
    }
    comma-dangle:
    - error
    - {
        arrays: always-multiline,
        objects: always-multiline
    }
    semi:
    - error
    - always
    no-undef:
    - 2
    - { typeof: true }
