version: "3"
services:
    web:
        build: docker
        ports:
            - 8888:8888
        command: npm run docker
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            HOST: 0.0.0.0
